import React, { useState } from 'react';
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';
import { Database, Activity, CheckCircle, Zap } from 'lucide-react';
import { BURSTGPT_PROFILE } from '../engine/scenarios';

export const BurstGptValidationView: React.FC = () => {
  const [selectedHour, setSelectedHour] = useState('11:00 AM');

  // Running time data (Figure 16a)
  const runningTimeData = [
    { vars: 50, time: 2.1 },
    { vars: 100, time: 8.5 },
    { vars: 150, time: 19.2 },
    { vars: 200, time: 34.0 },
    { vars: 250, time: 58.4 },
    { vars: 300, time: 92.1 },
    { vars: 350, time: 135.0 },
  ];

  return (
    <div id="burstgpt-validation-view" className="space-y-6">
      {/* Header Banner */}
      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-xs font-bold text-emerald-700 uppercase tracking-wider bg-emerald-50 px-2.5 py-0.5 rounded-full border border-emerald-200">
            Real-World Empirical Validation (Section VII & Appendix)
          </span>
        </div>
        <h1 className="text-xl font-bold text-slate-900 mt-1">
          BurstGPT Real-World LLM Dataset Validation & SPARQ Convergence
        </h1>
        <p className="text-xs text-slate-500 mt-0.5">
          Evaluating mathematical tractability assumptions using timestamped prompts and token traces from GPT-3.5 and GPT-4.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4 text-xs">
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <span className="text-slate-500 block">Assumption a):</span>
            <span className="font-semibold text-slate-900">Inter-Arrival Times ~ Poisson Process</span>
            <span className="text-[11px] text-emerald-600 block mt-0.5">Validated with 95th percentile fits</span>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <span className="text-slate-500 block">Assumption b1) GR:</span>
            <span className="font-semibold text-slate-900">Service Time ~ Negative Exponential</span>
            <span className="text-[11px] text-emerald-600 block mt-0.5">Single model dedicated GPU</span>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <span className="text-slate-500 block">Assumption b2) SR:</span>
            <span className="font-semibold text-slate-900">Cumulative Service ~ Mixture of Exponentials</span>
            <span className="text-[11px] text-indigo-600 block mt-0.5">Co-located GPT-3.5 & GPT-4 on GPU</span>
          </div>
        </div>
      </div>

      {/* Figures 14 & 15: Empirical Distribution Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Figure 15: Response Tokens Distribution */}
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs">
          <div className="flex items-center justify-between mb-2">
            <div>
              <h3 className="font-bold text-slate-900 text-sm">Figure 15: Response Token Length Distribution</h3>
              <p className="text-xs text-slate-500">GPT-3.5 vs GPT-4 with fitted exponential distributions</p>
            </div>
          </div>

          <div className="h-[280px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={BURSTGPT_PROFILE.tokenDistribution} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                <XAxis dataKey="bin" label={{ value: 'Response Tokens', position: 'insideBottom', offset: -5 }} fontSize={11} />
                <YAxis fontSize={11} />
                <Tooltip />
                <Legend wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
                <Bar dataKey="gpt35Prob" fill="#38bdf8" name="GPT-3.5 Empirical" radius={[3, 3, 0, 0]} />
                <Bar dataKey="gpt4Prob" fill="#818cf8" name="GPT-4 Empirical" radius={[3, 3, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <div className="text-[11px] text-slate-500 mt-2 bg-slate-50 p-2 rounded">
            <strong>Key Takeaway:</strong> Tokens generated by LLMs follow a clear exponential decay, confirming that
            the service time of AI inference requests can be accurately modeled by negative exponential distributions.
          </div>
        </div>

        {/* Figure 16b: Algorithm Convergence (RMSE vs Iterations) */}
        <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs">
          <div className="flex items-center justify-between mb-2">
            <div>
              <h3 className="font-bold text-slate-900 text-sm">Figure 16b: SPARQ Convergence Behavior</h3>
              <p className="text-xs text-slate-500">Root Mean Squared Error (RMSE) decay vs Iteration #</p>
            </div>
            <span className="px-2 py-0.5 text-[11px] bg-emerald-50 text-emerald-700 font-mono rounded">
              Converged in 10 iters
            </span>
          </div>

          <div className="h-[280px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={BURSTGPT_PROFILE.convergenceStats} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                <XAxis dataKey="iteration" label={{ value: 'Iteration #', position: 'insideBottom', offset: -5 }} fontSize={11} />
                <YAxis label={{ value: 'Average RMSE', angle: -90, position: 'insideLeft', offset: 25 }} fontSize={11} />
                <Tooltip />
                <Legend wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />
                <Line type="monotone" dataKey="rmse" stroke="#4f46e5" strokeWidth={2.5} name="Average RMSE" dot={{ r: 4 }} />
                <Line type="monotone" dataKey="gamma" stroke="#f59e0b" strokeWidth={1.5} strokeDasharray="4 2" name="Step Size γ_i" dot={{ r: 3 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
          <div className="text-[11px] text-slate-500 mt-2 bg-slate-50 p-2 rounded">
            <strong>Convergence Guarantee:</strong> Because the problem is decomposed into biconvex subproblems with diminishing
            step sizes γ_i, SPARQ smoothly converges to stationary points of Problem P in under 10-12 iterations.
          </div>
        </div>
      </div>

      {/* Figure 16a: Scalability & Running Time */}
      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs">
        <div className="flex items-center justify-between mb-2">
          <div>
            <h3 className="font-bold text-slate-900 text-sm">Figure 16a: Computational Performance & Scalability</h3>
            <p className="text-xs text-slate-500">
              Running time (s) as a function of the number of optimization variables |f_uv^k| + |μ_uv^{'{k,r}'}|
            </p>
          </div>
        </div>

        <div className="h-[240px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={runningTimeData} margin={{ top: 10, right: 20, left: -10, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="vars" label={{ value: 'Number of Variables |f_uv^k| + |μ_uv^{k,r}|', position: 'insideBottom', offset: -5 }} fontSize={11} />
              <YAxis label={{ value: 'Running Time (s)', angle: -90, position: 'insideLeft', offset: 20 }} fontSize={11} />
              <Tooltip />
              <Line type="monotone" dataKey="time" stroke="#0ea5e9" strokeWidth={2} name="Running Time (s)" dot={{ r: 4 }} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>
    </div>
  );
};
